# WindsurfAPI 首次引导 + 前台监督启动。
# 幂等生成项目根 .env(UTF-8 无 BOM),填缺失键,打印面板地址,进入监督循环。
# 前台运行(可见日志 + Ctrl-C 优雅停),最利首次调试。开机自启后台见 install-task.bat。

$ErrorActionPreference = 'Stop'

$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
Set-Location $Root
$EnvPath = Join-Path $Root '.env'

# ── 1. 预检 Node ≥ 20 ──────────────────────────────────────
function Stop-WithError([string]$msg, [string]$hint) {
  Write-Host ''
  Write-Host '============================================================' -ForegroundColor Red
  Write-Host " $msg" -ForegroundColor Red
  if ($hint) { Write-Host " $hint" -ForegroundColor Yellow }
  Write-Host '============================================================' -ForegroundColor Red
  Write-Host '按任意键退出...'
  $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')
  exit 1
}

$node = Get-Command node -ErrorAction SilentlyContinue
if (-not $node) {
  Stop-WithError 'Node.js 未安装或不在 PATH。' '请从 https://nodejs.org 安装 Node 20+ 后重试。'
}
$verRaw = (& node -v) -replace '^v', ''
$major = [int]($verRaw.Split('.')[0])
if ($major -lt 20) {
  Stop-WithError "Node 版本过低(当前 v$verRaw,需 ≥ 20)。" '请升级 Node.js 到 20 或更高。'
}

# ── 2. 强随机密钥(RandomNumberGenerator,非 Get-Random)──────
function New-Secret([int]$bytes = 24) {
  $buf = New-Object 'System.Byte[]' $bytes
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  $rng.GetBytes($buf)
  $rng.Dispose()
  # base64url:去掉 +/= 让密钥能安全放进 .env / URL / header
  return ([Convert]::ToBase64String($buf)) -replace '\+', '-' -replace '/', '_' -replace '=', ''
}

# ── 3. 幂等读取现有 .env(仅填缺失/占位键,保留用户已设值)──
$existing = @{}
$existingLines = @()
if (Test-Path $EnvPath) {
  try {
    $existingLines = Get-Content -Path $EnvPath -Encoding UTF8
    foreach ($line in $existingLines) {
      $t = $line.Trim()
      if (-not $t -or $t.StartsWith('#')) { continue }
      $eq = $t.IndexOf('=')
      if ($eq -lt 1) { continue }
      $k = $t.Substring(0, $eq).Trim()
      $v = $t.Substring($eq + 1).Trim()
      $existing[$k] = $v
    }
  } catch {
    # 无法解析:备份后重写(不丢用户数据)。
    $bak = "$EnvPath.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item $EnvPath $bak -Force
    Write-Host "现有 .env 无法解析,已备份到 $bak" -ForegroundColor Yellow
    $existing = @{}
  }
}

function Need-Key([string]$key) {
  return (-not $existing.ContainsKey($key)) -or [string]::IsNullOrWhiteSpace($existing[$key])
}

$generated = @{}
$genApiKey = $null
$genPassword = $null

if (Need-Key 'PORT')            { $generated['PORT'] = '3003' }
# HOST=127.0.0.1 必需:默认 0.0.0.0 + 空 API_KEY = fail-closed 锁死。
if (Need-Key 'HOST')            { $generated['HOST'] = '127.0.0.1' }
if (Need-Key 'API_KEY')         { $genApiKey = 'sk-windsurf-' + (New-Secret 24); $generated['API_KEY'] = $genApiKey }
if (Need-Key 'DASHBOARD_PASSWORD') { $genPassword = New-Secret 18; $generated['DASHBOARD_PASSWORD'] = $genPassword }
# DEVIN_CONNECT=1 必需:language_server 仅 Linux/macOS。
if ((Need-Key 'DEVIN_CONNECT') -and (Need-Key 'DEVIN_ONLY')) { $generated['DEVIN_CONNECT'] = '1' }

if ($generated.Count -gt 0) {
  # 合并:保留现有行,追加缺失键。
  $outLines = New-Object System.Collections.Generic.List[string]
  if ($existingLines.Count -gt 0) { foreach ($l in $existingLines) { $outLines.Add($l) } }
  if ($outLines.Count -gt 0 -and $outLines[$outLines.Count - 1].Trim() -ne '') { $outLines.Add('') }
  $outLines.Add("# --- generated by deploy/windows/start.ps1 $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ---")
  foreach ($k in $generated.Keys) { $outLines.Add("$k=$($generated[$k])") }

  # ⚠️ 必须无 BOM 写(UTF8Encoding($false))。虽然 config.js 的 .trim() 恰好能
  # 剥掉首键 BOM,仍以无 BOM 为规范,避免任何边缘键被 BOM 污染。
  $text = ($outLines -join "`r`n") + "`r`n"
  [System.IO.File]::WriteAllText($EnvPath, $text, (New-Object System.Text.UTF8Encoding($false)))
  Write-Host ".env 已更新(填入 $($generated.Count) 个缺失键)。" -ForegroundColor Green
} else {
  Write-Host '.env 已存在且完整,未改动。' -ForegroundColor Green
}

# ── 4. 端口预检(更快的友好提示;server.js 也会自重试 10x3s)──
$port = if ($generated.ContainsKey('PORT')) { $generated['PORT'] } elseif ($existing.ContainsKey('PORT')) { $existing['PORT'] } else { '3003' }
try {
  $listeners = [System.Net.NetworkInformation.IPGlobalProperties]::GetIPGlobalProperties().GetActiveTcpListeners()
  if ($listeners | Where-Object { $_.Port -eq [int]$port }) {
    Write-Host "警告:端口 $port 已被占用,启动可能失败(server.js 会重试 ~30s)。" -ForegroundColor Yellow
  }
} catch { }

# git 缺失告警(自更新需要)
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
  Write-Host '提示:未检测到 git,面板 Update / update.bat 自更新将不可用。' -ForegroundColor Yellow
}

# ── 5. 打印面板地址 + 密钥(仅本次生成的)──────────────────
Write-Host ''
Write-Host '============================================================' -ForegroundColor Cyan
Write-Host ' WindsurfAPI 已引导完成' -ForegroundColor Cyan
Write-Host "  面板:  http://127.0.0.1:$port/dashboard" -ForegroundColor White
if ($genPassword) { Write-Host "  面板密码 (DASHBOARD_PASSWORD):  $genPassword" -ForegroundColor Green }
if ($genApiKey)   { Write-Host "  API Key  (API_KEY):             $genApiKey" -ForegroundColor Green }
if (-not $genPassword -and -not $genApiKey) {
  Write-Host '  (密钥沿用现有 .env,如需查看请打开项目根 .env)' -ForegroundColor DarkGray
}
Write-Host ''
Write-Host ' 下一步:浏览器打开面板 → 用 DASHBOARD_PASSWORD 登录 → 到 accounts 页' -ForegroundColor White
Write-Host '         添加一个 Windsurf/Devin session token。' -ForegroundColor White
Write-Host '============================================================' -ForegroundColor Cyan
Write-Host ''

# ── 6. 进入前台监督循环 ────────────────────────────────────
& (Join-Path $PSScriptRoot 'run.ps1')
